### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by motaz** [wmnsk/go-tcap#1]
I suggest to have simple client/server project for go-tcap package, 
it will be easy to new comers to understand and use that package

**Comment by wmnsk** [comment]
Thank you for your suggestion.
I agree that having some examples help. I'll work on that some day I have time.

For your information, test code may help you understanding how to create/parse TCAP layer with this package. Both test cases("TCAP/Begin - AARQ - Invoke" and "TCAP/End - AARE - ReturnResultLast") creates full TCAP layers with the dummy payload(0xdeadbeef), and parses the bytes into structs.

https://github.com/wmnsk/go-tcap/blob/master/codec_test.go#L28-L97

**Comment by motaz** [comment]
Yes, test code will be useful for start, I'll check it
Thanks

**Comment by vazir** [comment]
> Thank you for your suggestion.
> I agree that having some examples help. I'll work on that some day I have time.
> 
> For your information, test code may help you understanding how to create/parse TCAP layer with this package. Both test cases("TCAP/Begin - AARQ - Invoke" and "TCAP/End - AARE - ReturnResultLast") creates full TCAP layers with the dummy payload(0xdeadbeef), and parses the bytes into structs.
> 
> https://github.com/wmnsk/go-tcap/blob/master/codec_test.go#L28-L97

Any hope you can provide a very short example for building a simplest MAP dialogue?

**Comment by wmnsk** [comment]
I have no plan to work on that, unfortunately.
