### ISSUE TITLE
how to run client

### ISSUE THREAD

**Issue by naseemr** [wmnsk/go-tcap#12]
I am new to go and following your instruction to run client. I am getting this error below:
go-tcap/examples/client# ./client -h
bash: ./client: No such file or directory

**Comment by naseemr** [comment]
I figured out how to run, now I am lost on how  do I configure sctp source port. Please help

**Comment by wmnsk** [comment]
Put local address in `m3ua.Dial`.

https://github.com/wmnsk/go-tcap/blob/master/examples/client/client.go#L67

**Comment by naseemr** [comment]
Thanks for your support.  so I had the following update:
m3conn, err := m3ua.Dial(ctx, "m3ua", "192.168.86.50:2092", raddr, m3config)

But getting error : ./client.go:67:40: cannot use "10.250.3.21:2092" (type string) as type *sctp.SCTPAddr in argument to m3ua.Dial

**Comment by wmnsk** [comment]
The error is telling you what you need. Like `raddr`, you should use `*sctp.SCTPAddr` instead of string.
